// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LogMessage.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
	LogLevel_FATAL   LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
	4: "FATAL",
}

var LogLevel_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
	"FATAL":   4,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92eb5d9068c7a100, []int{0}
}

type ApplicationLanguage int32

const (
	ApplicationLanguage_RUST ApplicationLanguage = 0
	ApplicationLanguage_JAVA ApplicationLanguage = 1
	ApplicationLanguage_CPP  ApplicationLanguage = 2
	ApplicationLanguage_GO   ApplicationLanguage = 3
)

var ApplicationLanguage_name = map[int32]string{
	0: "RUST",
	1: "JAVA",
	2: "CPP",
	3: "GO",
}

var ApplicationLanguage_value = map[string]int32{
	"RUST": 0,
	"JAVA": 1,
	"CPP":  2,
	"GO":   3,
}

func (x ApplicationLanguage) String() string {
	return proto.EnumName(ApplicationLanguage_name, int32(x))
}

func (ApplicationLanguage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92eb5d9068c7a100, []int{1}
}

type LogMessage struct {
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogLevel             LogLevel               `protobuf:"varint,2,opt,name=log_level,json=logLevel,proto3,enum=protobuf.LogLevel" json:"log_level,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	AppLang              ApplicationLanguage    `protobuf:"varint,4,opt,name=app_lang,json=appLang,proto3,enum=protobuf.ApplicationLanguage" json:"app_lang,omitempty"`
	Uid                  string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_92eb5d9068c7a100, []int{0}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LogMessage) GetLogLevel() LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return LogLevel_DEBUG
}

func (m *LogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogMessage) GetAppLang() ApplicationLanguage {
	if m != nil {
		return m.AppLang
	}
	return ApplicationLanguage_RUST
}

func (m *LogMessage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterEnum("protobuf.ApplicationLanguage", ApplicationLanguage_name, ApplicationLanguage_value)
	proto.RegisterType((*LogMessage)(nil), "protobuf.LogMessage")
}

func init() { proto.RegisterFile("LogMessage.proto", fileDescriptor_92eb5d9068c7a100) }

var fileDescriptor_92eb5d9068c7a100 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xc1, 0x4f, 0xfa, 0x30,
	0x14, 0xc7, 0x7f, 0xdd, 0x80, 0x6d, 0x8f, 0xe4, 0x97, 0xe6, 0x79, 0x59, 0x48, 0x8c, 0xc4, 0x13,
	0xe1, 0x30, 0x12, 0xbc, 0x10, 0x6f, 0x45, 0x81, 0x60, 0x26, 0x90, 0x0a, 0x7a, 0x24, 0x45, 0x6b,
	0xb3, 0xa4, 0xd0, 0x46, 0x36, 0xff, 0x5b, 0xff, 0x17, 0xd3, 0xcd, 0xb9, 0x8b, 0xa7, 0x7e, 0x5f,
	0xfb, 0x79, 0x9f, 0x6f, 0x81, 0xa6, 0x46, 0x3d, 0xca, 0xf3, 0x59, 0x28, 0x99, 0xd8, 0x0f, 0x93,
	0x1b, 0x0c, 0xcb, 0xe3, 0x50, 0xbc, 0xf7, 0xae, 0x94, 0x31, 0x4a, 0xcb, 0x51, 0x7d, 0x31, 0xca,
	0xb3, 0xa3, 0x3c, 0xe7, 0xe2, 0x68, 0x2b, 0xf4, 0xfa, 0x8b, 0x00, 0x34, 0xfb, 0x38, 0x81, 0xe8,
	0x97, 0x88, 0x49, 0x9f, 0x0c, 0xba, 0xe3, 0x5e, 0x52, 0x39, 0x92, 0xda, 0x91, 0x6c, 0x6b, 0x82,
	0x37, 0x30, 0x8e, 0x20, 0xd2, 0x46, 0xed, 0xb5, 0xfc, 0x94, 0x3a, 0xf6, 0xfa, 0x64, 0xf0, 0x7f,
	0x8c, 0xcd, 0x4a, 0x6a, 0x54, 0xea, 0x5e, 0x78, 0xa8, 0x7f, 0x12, 0xc6, 0x10, 0x1c, 0xab, 0xd6,
	0xd8, 0xef, 0x93, 0x41, 0xc4, 0xeb, 0x11, 0x27, 0x10, 0x0a, 0x6b, 0xf7, 0x5a, 0x9c, 0x54, 0xdc,
	0x2a, 0x4d, 0x97, 0x8d, 0x89, 0x59, 0xab, 0xb3, 0x57, 0x91, 0x67, 0xe6, 0x94, 0x8a, 0x93, 0x2a,
	0x84, 0x92, 0x3c, 0x10, 0xd6, 0xba, 0x01, 0x29, 0xf8, 0x45, 0xf6, 0x16, 0xb7, 0x4b, 0x9f, 0x8b,
	0xc3, 0x29, 0x84, 0x75, 0x37, 0x46, 0xd0, 0xbe, 0x9f, 0x4d, 0x77, 0x0b, 0xfa, 0x0f, 0x43, 0x68,
	0x2d, 0x57, 0xf3, 0x35, 0x25, 0xd8, 0x85, 0xe0, 0x85, 0xf1, 0xd5, 0x72, 0xb5, 0xa0, 0x9e, 0x23,
	0x66, 0x9c, 0xaf, 0x39, 0xf5, 0x5d, 0x9c, 0xb3, 0x2d, 0x4b, 0x69, 0x6b, 0x78, 0x0b, 0x17, 0x7f,
	0xb4, 0x3a, 0x07, 0xdf, 0x3d, 0x6d, 0x2b, 0xdb, 0x03, 0x7b, 0x66, 0x94, 0x60, 0x00, 0xfe, 0xdd,
	0x66, 0x43, 0x3d, 0xec, 0x80, 0xb7, 0x58, 0x53, 0xff, 0xd0, 0x29, 0x3f, 0x7e, 0xf3, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xde, 0x11, 0xf4, 0x53, 0xa5, 0x01, 0x00, 0x00,
}
